### PR TITLE
Issue 181 fix

### LINKED ISSUE #181: Fix issue in tremor as a library impacting rust-bench
Fix downstream issue in https://github.com/SchrodingerZhu/bench_suite/issues/7
impeding their progress with adding tremor-runtime to their rust-bench suite.

@mjp41 @SchrodingerZhu

Related - https://github.com/SchrodingerZhu/bench_suite/pull/8

Enhancement so that simd-json has native target support by default in downstream rust-bench

In a nutshell - tremor-runtime as a library may expose latent issues when type inference in rust is exercised in ways not intended by tremor-runtime per se, but necessary for downstream projects to be successful. Sometimes this is in ways we haven't designed but that we want to encourage!

**Notes**

### PR DESCRIPTION
**Pull request by darach**
Closes #181

Verified with rust-bench, PR to follow in downstream with build system changes related
to this fix.

```
cargo +nightly build --all
```

### CODE REVIEW

File: src/offramp/rest.rs [hunk 1]
```diff
@@ -76,7 +76,7 @@ impl Rest {
             use http::header::HeaderName;
             match HeaderName::from_bytes(k.as_str().as_bytes()) {
                 Ok(h) => {
-                    c = c.set_header(&h, v.as_str());
+                    c = c.set_header(&h, v.to_string());
```
Comment (Licenser) [inline src/offramp/rest.rs:79]: lets keep it as_str
```suggestion
                    c = c.set_header(&h, v.as_str());
```

**Comment by darach** [comment]
C'mon github actions... do your thing! 🤞 🕐
